# Generated by Django 5.0.6 on 2024-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_places_like_count_remove_subplaces_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplaces',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
