# Generated by Django 5.0.6 on 2024-09-20 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_subplaces_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplaces',
            name='image',
            field=models.FileField(blank=True, upload_to='subplaces/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
